version: '3.8'

services:
  backend:
    build: ./backend
    container_name: mern-backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - '5001:5001'
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    container_name: mern-frontend
    restart: always
    ports:
      - '3000:80'
    depends_on:
      - backend
