version: "3.9"

services:
  # Redis service
  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  # Backend (Express + Node.js)
  backend:
    build:
      context: ./client-api
      dockerfile: Dockerfile
    container_name: client-api
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./client-api/.env
    depends_on:
      - redis
    volumes:
      - ./client-api:/app          # Mount source code
      - /app/node_modules          # Keep container node_modules separate

  # Frontend (Vite + React + Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "3000:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
